// Este é o 5º arquivo de um total de 5 para anotações e estudos acerca de JS. Imagine que isso aqui é uma apostila interativa.

//********NOTA************ 
// Você pode executar os códigos dentro do proprio VSCODE utilizando da extensão do Code Runner, mas essa extensão não suporta alguns tipos de comandos,estruturas ou objetos, como aquelas que são executadas junto de um html, por exemplo.

// As funções são subprogramas que executam uma ou mais blocos de codigo encapsulados

    function calcularAreaTerreno (largura, comprimento){
        var area

    }